name: cd
on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/617705972231/locations/global/workloadIdentityPools/my-pool'
          service_account: 'cloud-run-deployer@nth-hybrid-454618-g8.iam.gserviceaccount'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.4
        with:
          version: '>= 363.0.0'

      - name: Verify gcloud authentication
        run: gcloud info

      - name: Build App
        run: scripts/buildprod.sh

      - name: Build Docker image
        run: |
          docker build -t flamme97/notely:latest .

      - name: Deploy to Artifact Registry
        run: |
          gcloud auth configure-docker europe-west10-docker.pkg.dev
          docker tag flamme97/notely:latest europe-west10-docker.pkg.dev/nth-hybrid-454618-g8/notely-ar-repo/notely:latest
          docker push europe-west10-docker.pkg.dev/nth-hybrid-454618-g8/notely-ar-repo/notely:latest
